# Generated by Django 5.0.6 on 2024-05-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_gathering_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='location_city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='location_country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='location_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='location_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='location_street',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='material_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='material_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='material_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='material_type',
            field=models.TextField(),
        ),
    ]
